### ISSUE TITLE
Robot Controller fails on startup

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [garrettsummerfi3ld/ohsrobotics-new-opencvtest#3]
# :x: BUG REPORT :x:

## Expected Behavior
Robot Controller launches with no errors

## Actual Behavior
Crashes on startup

## Steps to Reproduce the Problem

  1. Build current project
  1. Install project/APK on device
  1. Launch robot controller application

## Specifications

  - Version: n/A
  - Platform: 
      - Pixel 2 XL (9, API 28)
      - Galaxy S3 (7.1.2, API 25)
      - Galaxy S7 (8, API 26) (Thank you @ryanjokuti for testing)
  - OpMode: n/A

**Comment by garrettsummerfi3ld** [comment]
Logcat from Pixel 2 XL
```java
2018-10-06 15:12:31.109 32138-32138/com.qualcomm.ftcrobotcontroller E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qualcomm.ftcrobotcontroller, PID: 32138
    java.lang.RuntimeException: Unable to create application org.firstinspires.ftc.robotcore.internal.system.RobotApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.qualcomm.ftcrobotcontroller/org.firstinspires.ftc.robotcore.internal.files.MediaTransferProtocolMonitorService }: app is in background uid UidRecord{b5648de u0a229 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.qualcomm.ftcrobotcontroller/org.firstinspires.ftc.robotcore.internal.files.MediaTransferProtocolMonitorService }: app is in background uid UidRecord{b5648de u0a229 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
        at android.app.ContextImpl.startService(ContextImpl.java:1532)
        at android.content.ContextWrapper.startService(ContextWrapper.java:664)
        at org.firstinspires.ftc.robotcore.internal.system.ServiceController.startService(ServiceController.java:160)
        at org.firstinspires.ftc.robotcore.internal.system.ServiceController.autoStartServices(ServiceController.java:143)
        at org.firstinspires.ftc.robotcore.internal.system.ServiceController.onApplicationStart(ServiceController.java:69)
        at org.firstinspires.ftc.robotcore.internal.system.RobotApplication.onCreate(RobotApplication.java:53)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by garrettsummerfi3ld** [comment]
Investigating if ftctechnh/ftc_app@58d723a1d11a1c03ffb3a30f4a38c3601eac61d8 changes anything.

**Comment by garrettsummerfi3ld** [comment]
After commit 106842d574b8435e39678703766b0621a37a9308 same behavior is still happening.
Logcat from Pixel 2 XL
```java
2018-10-09 20:59:19.729 24058-24058/com.qualcomm.ftcrobotcontroller E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qualcomm.ftcrobotcontroller, PID: 24058
    java.lang.ExceptionInInitializerError
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes.<init>(RegisteredOpModes.java:95)
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes$InstanceHolder.<clinit>(RegisteredOpModes.java:70)
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes.getInstance(RegisteredOpModes.java:72)
        at com.google.blocks.ftcrobotcontroller.runtime.BlocksOpMode.addOpModeRegistrar(BlocksOpMode.java:575)
        at com.google.blocks.ftcrobotcontroller.runtime.BlocksOpMode.setActivityAndWebView(BlocksOpMode.java:557)
        at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:289)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: exception in extractJavaLibraryAsset()
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.extractJavaLibraryAsset(OnBotJavaManager.java:246)
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.extractAssets(OnBotJavaManager.java:220)
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.initialize(OnBotJavaManager.java:187)
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.<clinit>(OnBotJavaManager.java:180)
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes.<init>(RegisteredOpModes.java:95) 
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes$InstanceHolder.<clinit>(RegisteredOpModes.java:70) 
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes.getInstance(RegisteredOpModes.java:72) 
        at com.google.blocks.ftcrobotcontroller.runtime.BlocksOpMode.addOpModeRegistrar(BlocksOpMode.java:575) 
        at com.google.blocks.ftcrobotcontroller.runtime.BlocksOpMode.setActivityAndWebView(BlocksOpMode.java:557) 
        at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:289) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/FIRST/java/lib/android.jar (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at org.firstinspires.ftc.robotcore.internal.system.AppUtil.copyStream(AppUtil.java:412)
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.extractJavaLibraryAsset(OnBotJavaManager.java:239)
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.extractAssets(OnBotJavaManager.java:220) 
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.initialize(OnBotJavaManager.java:187) 
        at org.firstinspires.ftc.robotcore.internal.opmode.OnBotJavaManager.<clinit>(OnBotJavaManager.java:180) 
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes.<init>(RegisteredOpModes.java:95) 
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes$InstanceHolder.<clinit>(RegisteredOpModes.java:70) 
        at org.firstinspires.ftc.robotcore.internal.opmode.RegisteredOpModes.getInstance(RegisteredOpModes.java:72) 
        at com.google.blocks.ftcrobotcontroller.runtime.BlocksOpMode.addOpModeRegistrar(BlocksOpMode.java:575) 
        at com.google.blocks.ftcrobotcontroller.runtime.BlocksOpMode.setActivityAndWebView(BlocksOpMode.java:557) 
        at org.firstinspires.ftc.robotcontroller.internal.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:289) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by garrettsummerfi3ld** [comment]
Still performing same behavior with new update on Galaxy S7.

**Comment by garrettsummerfi3ld** [comment]
Reimported project, cleaned project after import, builds okay and runs without error.
